-- Clear existing projects
DELETE FROM public.projects;

-- Insert new projects from resume
INSERT INTO public.projects (title, description, image, technologies, github_url, live_url, featured) VALUES
('InfinityTech — E-Commerce Laptop Selling Platform', 'Full-featured e-commerce platform with product listings, category filtering, cart, checkout, order management, refunds, and admin controls. Razorpay payment integration with secure workflows (Delivered, Cancelled, Return Requests). JWT authentication + role-based access + inventory & discount modules. AWS S3 media storage, Cloudinary image optimization, EJS SSR, Docker containerization.', '/placeholder.svg', ARRAY['JavaScript', 'Node.js', 'Express.js', 'EJS', 'MongoDB', 'Mongoose', 'Razorpay', 'OAuth 2.0', 'Cloudinary', 'JWT', 'AWS S3', 'Docker', 'GitHub'], 'https://github.com', 'https://demo.com', true),
('Chatify — Real-Time Chat Application (MERN)', 'Real-time one-to-one chat with online/offline presence and typing status using Socket.io. Custom JWT authentication with secure authorization. Notifications + typing sounds with user-controlled toggle. Media sharing via Cloudinary, welcome emails via Resend. REST APIs with rate-limiting using Arcjet + MongoDB persistence. Responsive UI with React + Tailwind + DaisyUI, state management via Zustand.', '/placeholder.svg', ARRAY['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Socket.io', 'JWT', 'Cloudinary', 'Resend', 'Arcjet', 'Zustand', 'Tailwind CSS', 'DaisyUI', 'Git', 'GitHub'], 'https://github.com', 'https://demo.com', true),
('OLX Clone', 'React application with authentication, dynamic routing, reusable components, and Firebase integration.', '/placeholder.svg', ARRAY['React.js', 'Firebase', 'Authentication', 'Dynamic Routing'], 'https://github.com', 'https://demo.com', false),
('Netflix Clone', 'React application with authentication, dynamic routing, reusable components, and Firebase integration.', '/placeholder.svg', ARRAY['React.js', 'Firebase', 'Authentication', 'Dynamic Routing'], 'https://github.com', 'https://demo.com', false);
